import bb from "./images/blueberry.png";
import cherry from "./images/cherry.png";
import mango from "./images/mango.png";
import pf from "./images/passionfruit.png";
import pear from "./images/pear.png";
import pa from "./images/pineapple.png";



const data = [
    {sku: 10000, title: "Pear", weight: {value: 1, unit: "fruit"}, image: pear, backgroundColor: "#cc9900", price: 256, description: "Pears are fruits produced and consumed around the world, growing on a tree and harvested in late Summer into October.", nutritionInfo: {quantity: 100, calories: 57, fat: 0.1, cholesterol: 0, natrium: 0.001, kalium: 0.116, carbohydrates: 15, protein: 0.5}},
    {sku: 10001, title: "Pineapple", weight: {value: 1, unit: "fruit"}, image: pa, backgroundColor: "#ffff00", price: 488, description: "The pineapple is a tropical plant with an edible fruit and the most economically significant plant in the family Bromeliaceae.", nutritionInfo: {quantity: 100, calories: 50, fat: 0.1, cholesterol: 0, natrium: 0.001, kalium: 0.109, carbohydrates: 13, protein: 0.5}},
    {sku: 10002, title: "Blue Berries", weight: {value: 1, unit: "basket"}, image: bb, backgroundColor: "#003399", price: 299, description: "Blueberries are perennial flowering plants with blue or purple berries. They are classified in the section Cyanococcus within the genus Vaccinium.", nutritionInfo: {quantity: 100, calories: 57, fat: 0.3, cholesterol: 0, sodium: 0.001, fiber: 3.6, carbohydrates: 14, protein: 0.7}},
    {sku: 10003, title: "Cherries", weight: {value: 200, unit: "grams"}, image: cherry, backgroundColor: "#990000", price: 290, description: "A cherry is the fruit of many plants of the genus Prunus, and is a fleshy drupe (stone fruit).", nutritionInfo: {quantity: 100, calories: 50, fat: 0.3, cholesterol: 0, kalium: 0.173, natrium: 3, carbohydrates: 12, protein: 1}},
    {sku: 10004, title: "Mango", weight: {value: 1, unit: "fruit"}, image: mango, backgroundColor: "#ffcc00", price: 190, description: "A mango is a stone fruit produced from numerous species of tropical trees belonging to the flowering plant genus Mangifera, cultivated mostly for their edible fruit. Most of these species are found in nature as wild mangoes.", nutritionInfo: {quantity: 100, calories: 60, fat: 0.4, cholesterol: 0, sodium: 0.001, fibre: 1.5, carbohydrates: 15, protein: 0.8}},
    {sku: 10005, title: "Passion fruit", weight: {value: 3, unit: "fruits"}, image: pf, backgroundColor: "#ff9900", price: 499, description: "The passion fruit is so called because it is one of the many species of passion flower, the English translation of the Latin genus name, Passiflora.", nutritionInfo: {quantity: 100, calories: 97, fat: 0.7, cholesterol: 0, natrium: 0.028, kalium: 0.348, carbohydrates: 23, protein: 2.2}},
    {sku: 10000, title: "Pear", weight: {value: 1, unit: "fruit"}, image: pear, backgroundColor: "#cc9900", price: 256, description: "Pears are fruits produced and consumed around the world, growing on a tree and harvested in late Summer into October.", nutritionInfo: {quantity: 100, calories: 57, fat: 0.1, cholesterol: 0, natrium: 0.001, kalium: 0.116, carbohydrates: 15, protein: 0.5}},
    {sku: 10001, title: "Pineapple", weight: {value: 1, unit: "fruit"}, image: pa, backgroundColor: "#ffff00", price: 488, description: "The pineapple is a tropical plant with an edible fruit and the most economically significant plant in the family Bromeliaceae.", nutritionInfo: {quantity: 100, calories: 50, fat: 0.1, cholesterol: 0, natrium: 0.001, kalium: 0.109, carbohydrates: 13, protein: 0.5}},
    {sku: 10002, title: "Blue Berries", weight: {value: 1, unit: "basket"}, image: bb, backgroundColor: "#003399", price: 299, description: "Blueberries are perennial flowering plants with blue or purple berries. They are classified in the section Cyanococcus within the genus Vaccinium.", nutritionInfo: {quantity: 100, calories: 57, fat: 0.3, cholesterol: 0, sodium: 0.001, fiber: 3.6, carbohydrates: 14, protein: 0.7}},
    {sku: 10003, title: "Cherries", weight: {value: 200, unit: "grams"}, image: cherry, backgroundColor: "#990000", price: 290, description: "A cherry is the fruit of many plants of the genus Prunus, and is a fleshy drupe (stone fruit).", nutritionInfo: {quantity: 100, calories: 50, fat: 0.3, cholesterol: 0, kalium: 0.173, natrium: 3, carbohydrates: 12, protein: 1}},
    {sku: 10004, title: "Mango", weight: {value: 1, unit: "fruit"}, image: mango, backgroundColor: "#ffcc00", price: 190, description: "A mango is a stone fruit produced from numerous species of tropical trees belonging to the flowering plant genus Mangifera, cultivated mostly for their edible fruit. Most of these species are found in nature as wild mangoes.", nutritionInfo: {quantity: 100, calories: 60, fat: 0.4, cholesterol: 0, sodium: 0.001, fibre: 1.5, carbohydrates: 15, protein: 0.8}},
    {sku: 10005, title: "Passion fruit", weight: {value: 3, unit: "fruits"}, image: pf, backgroundColor: "#ff9900", price: 499, description: "The passion fruit is so called because it is one of the many species of passion flower, the English translation of the Latin genus name, Passiflora.", nutritionInfo: {quantity: 100, calories: 97, fat: 0.7, cholesterol: 0, natrium: 0.028, kalium: 0.348, carbohydrates: 23, protein: 2.2}},
    // {sku: 10000, title: "Pear", weight: {value: 1, unit: "fruit"}, image: pear, backgroundColor: "#cc9900", price: 256, description: "Pears are fruits produced and consumed around the world, growing on a tree and harvested in late Summer into October.", nutritionInfo: {quantity: 100, calories: 57, fat: 0.1, cholesterol: 0, natrium: 0.001, kalium: 0.116, carbohydrates: 15, protein: 0.5}},
    // {sku: 10001, title: "Pineapple", weight: {value: 1, unit: "fruit"}, image: pa, backgroundColor: "#ffff00", price: 488, description: "The pineapple is a tropical plant with an edible fruit and the most economically significant plant in the family Bromeliaceae.", nutritionInfo: {quantity: 100, calories: 50, fat: 0.1, cholesterol: 0, natrium: 0.001, kalium: 0.109, carbohydrates: 13, protein: 0.5}},
    // {sku: 10002, title: "Blue Berries", weight: {value: 1, unit: "basket"}, image: bb, backgroundColor: "#003399", price: 299, description: "Blueberries are perennial flowering plants with blue or purple berries. They are classified in the section Cyanococcus within the genus Vaccinium.", nutritionInfo: {quantity: 100, calories: 57, fat: 0.3, cholesterol: 0, sodium: 0.001, fiber: 3.6, carbohydrates: 14, protein: 0.7}},
    // {sku: 10003, title: "Cherries", weight: {value: 200, unit: "grams"}, image: cherry, backgroundColor: "#990000", price: 290, description: "A cherry is the fruit of many plants of the genus Prunus, and is a fleshy drupe (stone fruit).", nutritionInfo: {quantity: 100, calories: 50, fat: 0.3, cholesterol: 0, kalium: 0.173, natrium: 3, carbohydrates: 12, protein: 1}},
    // {sku: 10004, title: "Mango", weight: {value: 1, unit: "fruit"}, image: mango, backgroundColor: "#ffcc00", price: 190, description: "A mango is a stone fruit produced from numerous species of tropical trees belonging to the flowering plant genus Mangifera, cultivated mostly for their edible fruit. Most of these species are found in nature as wild mangoes.", nutritionInfo: {quantity: 100, calories: 60, fat: 0.4, cholesterol: 0, sodium: 0.001, fibre: 1.5, carbohydrates: 15, protein: 0.8}},
    // {sku: 10005, title: "Passion fruit", weight: {value: 3, unit: "fruits"}, image: pf, backgroundColor: "#ff9900", price: 499, description: "The passion fruit is so called because it is one of the many species of passion flower, the English translation of the Latin genus name, Passiflora.", nutritionInfo: {quantity: 100, calories: 97, fat: 0.7, cholesterol: 0, natrium: 0.028, kalium: 0.348, carbohydrates: 23, protein: 2.2}},
]

export default data;